# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]

koin = "3.2.2"
ktor = "2.1.3"

[libraries]

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
server-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
server-freemarker-jvm = { module = "io.ktor:ktor-server-freemarker-jvm", version.ref = "ktor" }
server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
server-tests = { module = "io.ktor:ktor-server-tests", version.ref = "ktor" }
server-content-negotiation-jvm = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
